### ISSUE TITLE
Fails to build on Slackware64 14.2

### ISSUE THREAD

**Issue by zoot** [sapo/kyoto#21]
Hi there

I discovered a build bug when compiling under Slackware64 14.2

The build failed with:
```
g++ -g -O2 -Wall -fPIC -fsigned-char -g0 -O2 -Wno-unused-but-set-variable -Wno-unused-but-set-parameter -o ktserver ktserver.o myscript.o \
  -L. -L/pkg/kyototycoon-al/20170410/lib -L/usr/local/lib -L/usr/local/lib/lua -L/pkg/kyotocabinet-al/20170410/lib -L/pkg/lua/5.1.5/lib -Wl,-rpath-link,.:/usr/local/lib:.:/usr/local/lib::/usr/local/lib/lua:/pkg/kyotocabinet-al/20170410/lib:/pkg/lua/5.1.5/lib -Wl,--as-needed  -lkyototycoon -lkyotocabinet -llua
/usr/lib64/gcc/x86_64-slackware-linux/5.3.0/../../../../x86_64-slackware-linux/bin/ld: /pkg/lua/5.1.5/lib/liblua.a(loadlib.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/lib64/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:535: recipe for target 'ktserver' failed
```

So, searching the web for:
```
"liblua.a(loadlib.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'"
```
... led me to this [link](https://www.mail-archive.com/haproxy@formilux.org/msg18656.html)

... which states:
```
-ldl where dlclose@@GLIBC_2.2.5 should be after -llua, where this symbol is used.
```
So I patched the Makefile as follows to correct the issue:

```
cd /path/to/kyoto/kyototycoon
sed -i 's/CMDLIBS =  -lkyotocabinet -llua/CMDLIBS =  -lkyotocabinet -llua -ldl/' Makefile
```

**Comment by carlosefr** [comment]
I can't reproduce this issue on macOS, Debian or CentOS, but I've commited a tentative fix (https://github.com/carlosefr/kyoto/commit/4d77ac4282ead2bcb620c7ab6b9bcb3d2eb31220) that doesn't involve modifying files created during the build process. Can you try building from my fork[1] and see if it solves it?

[1] https://github.com/carlosefr/kyoto

**Comment by zoot** [comment]
Morning Carlos

I had the same reservations regarding patching the Makefile itself.

Yes, that resolves it, thank you.

**Comment by carlosefr** [comment]
Great. 👍
